FROM ubuntu:21.10

# Setup user
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Setup timezone info
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Grab dependencies
RUN apt-get upgrade -y && apt-get install -y wget git

RUN mkdir -p /src
WORKDIR /src

# Install Go
RUN wget https://golang.org/dl/go1.17.3.linux-amd64.tar.gz
RUN tar -C /usr/local/ -xzf go1.17.3.linux-amd64.tar.gz
ENV PATH=${PATH}:/usr/local/go/bin:/home/${USERNAME}/go/bin

# Install Hugo
RUN git clone https://github.com/gohugoio/hugo.git
WORKDIR /src/hugo
USER ${USERNAME}
RUN go install
USER root

# Create the workspace
RUN mkdir -p /workspace