FROM ubuntu:22.04

# Setup user
ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

# Setup timezone info
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Grab dependencies
RUN apt-get upgrade -y && apt-get install -y wget git

RUN mkdir -p /src
WORKDIR /src

# Install Go
RUN wget https://go.dev/dl/go1.11.linux-amd64.tar.gz
RUN tar -C /usr/local/ -xzf go1.11.linux-amd64.tar.gz
ENV PATH=${PATH}:/usr/local/go/bin:/home/${USERNAME}/go/bin

# Install Hugo
RUN wget https://github.com/gohugoio/hugo/releases/download/v0.101.0/hugo_0.101.0_Linux-64bit.tar.gz
RUN tar -C /bin -xzf hugo_0.101.0_Linux-64bit.tar.gz
RUN chmod +x /bin/hugo
USER root

# Create the workspace
RUN mkdir -p /workspace
RUN chown -R ${USER_UID} /workspace
RUN chgrp -R ${USER_GID} /workspace
USER ${USERNAME}