baseURL: "https://caltona.net/"
languageCode: "en-us"
title: "Christopher Altona"
theme: "PaperMod"

params:
  profileMode:
    enabled: true
    subtitle: "My personal website"
    buttons:
      - name: "Posts"
        url: "/posts/"
      - name: "CV"
        url: "/cv/"
  socialIcons:
    - name: "GitHub"
      url: "https://github.com/D3v01dZA"
    - name: "RSS"
      url: "/index.xml"
  ShowReadingTime: true
  ShowCodeCopyButtons: true

menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 10
    - identifier: CV
      name: CV
      url: /cv/
      weight: 20